[book]
authors = ["Dr. Fritz Haas"]
language = "ie"
multilingual = false
src = "src"
title = "Grammatica de Interlingue"
description = ""

[output.html]
theme = "src/theme"
default-theme = "rust"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/occidental-lang/Grammatica-de-Interlingue"
site-url = "/Grammatica-de-Interlingue/"
google-analytics = "UA-151655688-1"

[output.html.fold]
enable = true
level = 0

[build]
build-dir = "docs"
